create table members(
mb_no int(11) not null auto_increment,
mb_id varchar(20) not null default '',
mb_password varchar(255) not null default '',
mb_name varchar(255) not null default '',
mb_email varchar(255) not null default '',
mb_birth varchar(255) not null default '',
mb_level tinyint(4) not null default '0',
mb_sex char(1) not null default '',
mb_tel varchar(255) not null default '',
mb_hp varchar(255) not null default '',
mb_certify varchar(20) not null default '',
mb_postcode varchar(255) not null default '',
mb_add1 varchar(255) not null default '',
mb_add2 varchar(255) not null default '',
mb_add_jibun varchar(255) not null default '',
mb_sms tinyint(4) not null default '0',
mb_mailing tinyint(4) not null default '0',
mb_email_certify varchar(20) not null default '',
mb_hp_certify varchar(20) not null default '',
mb_datetime datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY (`mb_no`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;